server:
  port: 8080
  shutdown: graceful
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    show-sql:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics'
